### PR TITLE
Add contents to the repository

### PR DESCRIPTION
**Pull request by mm-pazouki**
Add required HTML files.
Add required CSS and JS files.
Add images and fonts.

### CODE REVIEW

**Comment by topeogunleye** [comment]
@mm-pazouki please kindly fix your linter errors. DM me if you're unable  to

**Comment by mm-pazouki** [comment]
> @mm-pazouki please kindly fix your linter errors. DM me if you're unable to

done

**Comment by topeogunleye** [comment]
> > @mm-pazouki please kindly fix your linter errors. DM me if you're unable to
> 
> done

@mm-pazouki , well done

please update your README file

**Comment by mm-pazouki** [comment]
> > > @mm-pazouki please kindly fix your linter errors. DM me if you're unable to
> > 
> > 
> > done
> 
> @mm-pazouki , well done
> 
> please update your README file

done

**Review by topeogunleye — APPROVED** [review]
Hi @mm-pazouki, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

> ## (Highlights) Good Points: 💪 
- Good job on adding an “Acknowledgements” section to the README file and giving proper credit to Cindy Shin for the original design. This shows respect for the work of others and compliance with the Creative Commons License.👏 ✔️ 
- The project structure and navigation are well implemented, with a Home page and About page. ✔️ 
- Navigation between the pages is smooth, with clear links from Home to About and vice versa. ✔️
- The navbar is well-designed and responsive. ✔️
  - On mobile, it features a hamburger menu and a transparent or matching background. ✔️
  - On desktop, it has a top dark bar with social media links, logout, and language links aligned to the right. The bottom white bar contains the logo and page links. ✔️
- The footer is appropriately designed with a logo aligned to the left and text aligned to the right. ✔️
  - On mobile, it has a white background, and on desktop, the About page has a dark background while the Home page has a white background. ✔️
- The Home page is structured effectively with top, middle, and bottom sections, each containing the necessary elements such as text, articles, images, and descriptions. The layout adapts well to both mobile and desktop sizes. ✔️
- The About page is also well-structured, featuring top, middle, and bottom sections, and the layout adjusts gracefully for both mobile and desktop sizes. ✔️
- The design and styling are consistent with the original design, utilizing the specified colors, fonts, spacing, borders, shadows, and paddings. ✔️
- The HTML code demonstrates good practices, utilizing semantic tags appropriately, incorporating clear hierarchies, including alt attributes for images, and ensuring accessibility. ✔️
- The CSS code is well-organized and avoids repetition, with selector classes used effectively. The styling follows a mobile-first approach and utilizes media queries for responsive design. ✔️
- The JavaScript code successfully generates dynamic HTML for the "Featured speakers" section, following best practices by placing the code in a separate .js file and using an array or object to store the list of speakers. The generated content is appropriately attached to the static HTML. ✔️

çrpik-kurdî-impressive



Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear
Please, remember to tag @topeogunleye in your question so I can receive the notification.
 
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
